temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", temp)
unzip(temp,list=TRUE)
temp1 = tempfile()
temp2 <- tempfile()
temp1 <- unzip(temp, "Source_Classification_Code.rds")
temp2 <- unzip(temp,"summarySCC_PM25.rds")
SCC <- readRDS(temp2)
Summary <- readRDS(temp1)
write.table(Summary,"Summary.txt")
Summary <- read.table("Summary.txt", header = TRUE, , colClass=c("character","character","factor",rep("character",13)))
head(SCC)
head(Summary)
library(ggplot2)
total <- tapply(scc1$Emissions, list(scc1$year, scc1$type),sum)
y=round(c(total[1,],total[2,],total[3,],total[4,]),digits=2)
y2 <- cbind(y, rep(c(1999,2002,2005,2008),each = 4),rep(colnames(total),4))
data <- data.frame(y2, row.names=NULL)
data <- transform(data, V3 = factor(V3))
qplot(V2,y,data = data, facets=V3~. ,geom= "auto")
dev.copy(png, "plot3.png", width = 480, height = 480)
dev.off()