temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", temp)
unzip(temp,list=TRUE)
temp1 = tempfile()
temp2 <- tempfile()
temp1 <- unzip(temp, "Source_Classification_Code.rds")
temp2 <- unzip(temp,"summarySCC_PM25.rds")
SCC <- readRDS(temp2)
Summary <- readRDS(temp1)
write.table(Summary,"Summary.txt")
Summary <- read.table("Summary.txt", header = TRUE, , colClass=c("character","character","factor",rep("character",13)))
head(SCC)
head(Summary)
scc1 <- subset(SCC, fips=="24510")
resultList <- grep("coal", Summary$SCC.Level.One)
x <- matrix(0, ncol=10000, nrow=ncol(Summary)-2)
resu1 <- unique(grep("[c|C]ombustion", Summary$SCC.Level.One,value = TRUE))
resu2 <- unique(grep("[c|C]ombustion", Summary$SCC.Level.Two,value = TRUE))
resu3 <- unique(grep("[c|C]ombustion", Summary$SCC.Level.Three,value = TRUE))
resu <- subset(Summary, Summary$SCC.Level.One %in% resu1 | Summary$SCC.Level.Two %in% resu2 | Summary$SCC.Level.Three %in% resu3)
resu0 <- resu[grep("[c|C]oal", resu$Short.Name, value= FALSE),]
dim(resu0)
id <- unique(resu0$SCC)
id
scc2 <- subset(scc1, scc1$SCC %in% id)
boxplot(Emissions~year, scc2, col = "Red")
total2 <- tapply(scc2$Emissions, list(scc2$year),sum)
plot(c("1999","2002","2005", "2008"),total2,type="l", lwd = 4, col = "Blue", xlab = "Year",ylab = "Emissions", main = "Emissions change from Coal Combustions")
dev.copy(png,"plot4.png")
dev.off()