temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", temp)
unzip(temp,list=TRUE)
temp1 = tempfile()
temp2 <- tempfile()
temp1 <- unzip(temp, "Source_Classification_Code.rds")
temp2 <- unzip(temp,"summarySCC_PM25.rds")
SCC <- readRDS(temp2)
Summary <- readRDS(temp1)
write.table(Summary,"Summary.txt")
Summary <- read.table("Summary.txt", header = TRUE, , colClass=c("character","character","factor",rep("character",13)))
head(SCC)
head(Summary)
scc4 <- subset(SCC, fips=="06037")
scc5 <- subset(scc4, scc4$SCC %in% unique(motor$SCC))
total4 <- tapply(scc5$Emissions, scc5$year,sum)
plot(c("1999","2002","2005", "2008"),total4,type="l", lwd = 4, col = "Green", xlab = "Year",ylab = "Emissions", main = "Emissions change from Motor Source")
sd(total3)
sd(total4)
total <- as.data.frame(c(total3, total4))
total$city <- rep(c("Baltimore", "Los Angeles"), each = 4)
total$year <- rep(c("1999","2002","2005","2008"),2)
colnames(total) <- c("Emissions", "City","year")
library(ggplot2)
qplot(year , Emissions, data = total, col = City, geom = "path")
g <- ggplot(total, aes(x = year, y = Emissions,col = City))
g + geom_point()+geom_line(aes(group = City))
dev.copy(png, "plot6.png")
dev.off()