temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", temp)
unzip(temp,list=TRUE)
temp1 = tempfile()
temp2 <- tempfile()
temp1 <- unzip(temp, "Source_Classification_Code.rds")
temp2 <- unzip(temp,"summarySCC_PM25.rds")
SCC <- readRDS(temp2)
Summary <- readRDS(temp1)
write.table(Summary,"Summary.txt")
Summary <- read.table("Summary.txt", header = TRUE, , colClass=c("character","character","factor",rep("character",13)))
head(SCC)
head(Summary)
scc1 <- subset(SCC, fips=="24510")
total <- tapply(scc1$Emissions, scc1$year, sum)
plot(c("1999","2002","2005", "2008"),total,type="l", lwd = 4, col = "Blue", xlab = "Year",ylab = "Total Emissions", main = "Emissions change in Baltimore City")
dev.copy(png, "plot2.png", width = 480, height = 480)
dev.off()