temp = tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", temp)
unzip(temp,list=TRUE)
temp1 = tempfile()
temp2 <- tempfile()
temp1 <- unzip(temp, "Source_Classification_Code.rds")
temp2 <- unzip(temp,"summarySCC_PM25.rds")
SCC <- readRDS(temp2)
Summary <- readRDS(temp1)
write.table(Summary,"Summary.txt")
Summary <- read.table("Summary.txt", header = TRUE, , colClass=c("character","character","factor",rep("character",13)))
head(SCC)
head(Summary)
scc1 <- subset(SCC, fips=="24510")
motor <- Summary[grep("[M|m]otor", Summary$Short.Name, value= FALSE),]
scc3 <- subset(scc1, scc1$SCC %in% unique(motor$SCC))
total3 <- tapply(scc3$Emissions,scc3$year,sum)
plot(c("1999","2002","2005", "2008"),total3,type="l", lwd = 4, col = "Red", xlab = "Year",ylab = "Emissions", main = "Emissions change from Motor Source")
dev.copy(png,"plot5.png")
dev.off()